# Generated by Django 4.1.4 on 2022-12-06 16:43

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User(name="David William", email="david@gmail.com", document="24343434", phone="123456789").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
